on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: [self-hosted, data-platform, ubuntu, ARM64, 4cpu16ram]
    steps:
      - run: echo "$GITHUB_OUTPUT"
      - run: echo 'foo bar'
      - run: echo "::notice title=Hello::foobar runner's spot instance was evicted by Azure for capacity. Re-trigger this job"
      - run: sleep 3600
